#!/usr/bin/env bash
# Render the documentation site into site/.
#
#   bash .github/scripts/build-docs-site.sh
#
# Lives here rather than in the shared scripts folder because the docs workflow
# runs from a checkout of this repository alone and cannot reach anything
# outside it. Runs locally too, for previewing before pushing.
#
# The prose is docs/*.md, written for the site. It used to be README.md rendered
# straight through, which gave a site that was one page long, opened with three
# shields.io badges and had nothing to navigate to. A README answers "should I
# use this" for somebody looking at a repository; a documentation site answers
# "how do I do X" for somebody who already decided. They are different documents
# and the README stays as it is for GitHub.
#
# The API reference under /apidocs/ is generated by pdoc from the docstrings in
# src/. It is part of the site rather than an afterthought: unlike Go, which has
# pkg.go.dev building a reference from the source of every published version,
# Python has nowhere that does this for a package, so nothing else will host it.
# Generating it from the same commit as the prose is what stops the two drifting
# apart.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"
OUT="site"

command -v pandoc >/dev/null || { echo "pandoc is required" >&2; exit 1; }
command -v pdoc >/dev/null || { echo "pdoc is required: pip install pdoc" >&2; exit 1; }

# The same question the workflow's link check asks of the site, asked of the
# source instead.
#
# Links between pages are written as .md and rewritten to .html below, for the
# rendered copy only. That convention exists so the same files read correctly on
# GitHub, which is where somebody meets these pages before they find the site --
# and the site check cannot see that half. It runs on the rewritten output in
# site/, so it is satisfied by `guide.html` existing there whatever the markdown
# said. A cross-page link written `.html` in the source would render to a page
# that works and stay dead in GitHub's markdown view, invisible to every check
# the build has: that is exactly how acemq-java-amqp carried 75 of them for
# months, found by somebody reading docs/ in the repository rather than by CI.
#
# It runs first because it needs nothing rendered -- neither pandoc nor pdoc --
# and a bad link is cheapest to find before a minute of rendering.
python3 - <<'PY'
import os, re, sys, urllib.parse

DOCS = "docs"

pages = sorted(f for f in os.listdir(DOCS) if f.endswith(".md"))
broken = []
links = 0

for page in pages:
    with open(os.path.join(DOCS, page), encoding="utf-8") as handle:
        body = handle.read()
    for target in re.findall(r"\]\(([^)\s]+)\)", body):
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        path = urllib.parse.unquote(target.partition("#")[0])
        if not path:
            continue
        links += 1
        # The generated API reference is genuinely HTML: pdoc writes it into
        # site/apidocs/, no markdown renders into it, and there is no .md any
        # link could have named instead. Any other .html target is a docs page
        # written the wrong way round -- the mistake this check exists for, so
        # it is named as that rather than reported as a missing file.
        if path.endswith(".html"):
            if not path.startswith("apidocs/"):
                broken.append("{} -> {}  (a docs page link belongs in .md)".format(page, target))
            continue
        if not os.path.exists(os.path.join(DOCS, path)):
            broken.append("{} -> {}".format(page, target))

if broken:
    print("::error::docs/ links that are dead when the pages are read on GitHub:")
    for item in broken:
        print("  " + item)
    sys.exit(1)
print("{} source pages, {} internal links, every one resolves inside docs/"
      .format(len(pages), links))
PY

# The option was renamed: --highlight-style in older pandoc,
# --syntax-highlighting in newer, and each rejects or deprecates the other.
# Ubuntu's package and a current Homebrew install sit on opposite sides of that
# change, so the flag is chosen rather than assumed.
if pandoc --help 2>&1 | grep -q -- '--syntax-highlighting'; then
  HIGHLIGHT=(--syntax-highlighting=tango)
else
  HIGHLIGHT=(--highlight-style=tango)
fi

rm -rf "$OUT"
mkdir -p "$OUT"

# Images as well as stylesheets. Copying only *.css is how a logo ends up
# referenced by every page and served by none.
if compgen -G "docs/assets/*" > /dev/null; then
  mkdir -p "$OUT/assets"
  cp docs/assets/* "$OUT/assets/"
fi

cat > "$OUT/style.css" <<'CSS'
:root {
  color-scheme: light dark;
  --fg:#1a1a1a; --bg:#fff; --muted:#5f5f5f; --line:#e4e4e4;
  --accent:#b4451f; --code-bg:#f7f7f5; --nav-bg:#fbfbfa;
}
@media (prefers-color-scheme: dark) {
  :root { --fg:#e8e8e8; --bg:#161616; --muted:#9c9c9c; --line:#2d2d2d;
          --accent:#ff8a5c; --code-bg:#1e1e1e; --nav-bg:#1b1b1b; }
}
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font:16px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
nav.top { background:var(--nav-bg); border-bottom:1px solid var(--line);
          padding:.85rem 1.25rem; display:flex; gap:1.15rem; flex-wrap:wrap; align-items:baseline;
          position:sticky; top:0; z-index:10; }
nav.top .brand { display:inline-flex; align-items:center; gap:.5rem; font-weight:700;
                 letter-spacing:-.01em; margin-right:.5rem; }
nav.top .brand img { height:22px; width:auto; display:block; }
/* The mark is black on transparent, so it disappears against a dark page.
   Inverting is enough for a two-tone logo and avoids shipping a second file. */
@media (prefers-color-scheme: dark) { nav.top .brand img { filter: invert(1) brightness(1.15); } }
nav.top a { color:var(--fg); text-decoration:none; font-size:.9rem; opacity:.78; }
nav.top a:hover { opacity:1; color:var(--accent); }
nav.top a.enterprise { color:var(--fg); opacity:.78; }
nav.top a.enterprise:hover { opacity:1; color:var(--accent); }
/* The right-hand group: the destinations somebody arrives looking for, rather
   than the page-by-page guide. Tutorials carries the auto margin, so the group
   stays together however many guide pages are added to its left. */
nav.top a.tutorials { color:var(--accent); opacity:1; font-weight:600; }
nav.top a.api { color:var(--accent); opacity:1; font-weight:600; }

/* Grouped navigation. No JavaScript: the menu opens on hover and on focus-within,
   so a keyboard reaches it and a blocked script cannot break it. */
nav.top .group { position:relative; display:inline-block; }
nav.top .group > button { font:inherit; font-size:.9rem; color:var(--fg); opacity:.78;
  background:none; border:0; padding:0; cursor:pointer; }
nav.top .group > button::after { content:" \25be"; font-size:.8em; opacity:.7; }
nav.top .group:hover > button, nav.top .group:focus-within > button {
  opacity:1; color:var(--accent); }
nav.top .group .menu { display:none; position:absolute; left:0; top:100%; z-index:20;
  background:var(--nav-bg); border:1px solid var(--line); border-radius:8px;
  padding:.4rem 0; min-width:15rem; box-shadow:0 6px 24px rgba(0,0,0,.12); }
nav.top .group:hover .menu, nav.top .group:focus-within .menu { display:block; }
nav.top .group .menu a { display:block; padding:.35rem 1rem; opacity:.85; white-space:nowrap; }
nav.top .group .menu a:hover { background:var(--code-bg); opacity:1; }
nav.top a.enterprise:first-of-type { margin-left:auto; }

/* On a narrow screen the menus would hang off the edge, so everything unfolds
   into a list instead of pretending to be a menu bar. */
@media (max-width: 900px) {
  nav.top { flex-wrap:wrap; }
  nav.top .group { position:static; }
  nav.top .group .menu { position:static; display:block; border:0; box-shadow:none;
    padding:0; background:none; min-width:0; }
  nav.top .group > button { display:none; }
  nav.top .group .menu a { display:inline-block; padding:0; }
  nav.top a.enterprise:first-of-type { margin-left:0; }
}
main { max-width:47rem; margin:0 auto; padding:2.5rem 1.25rem 5rem; }
h1 { font-size:2rem; letter-spacing:-.025em; margin:0 0 1.5rem; }
h2 { font-size:1.3rem; letter-spacing:-.015em; margin:2.75rem 0 .85rem;
     padding-top:.4rem; border-top:1px solid var(--line); }
h3 { font-size:1.05rem; margin:1.75rem 0 .6rem; }
p, li { color:var(--fg); }
a { color:var(--accent); }
pre { background:var(--code-bg); border:1px solid var(--line); border-radius:8px;
      padding:1rem 1.15rem; overflow-x:auto; font-size:.855rem; line-height:1.55; }
code { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.9em; }
p code, li code, td code { background:var(--code-bg); border:1px solid var(--line);
      border-radius:4px; padding:.08em .35em; color:var(--accent); }
pre code { background:none; border:none; padding:0; color:inherit; }
table { border-collapse:collapse; width:100%; font-size:.92rem; display:block; overflow-x:auto; }
th,td { text-align:left; padding:.55rem .8rem; border-bottom:1px solid var(--line); vertical-align:top; }
th { color:var(--muted); font-weight:600; }
blockquote { border-left:3px solid var(--line); margin:1.25rem 0; padding:.2rem 0 .2rem 1.15rem; color:var(--muted); }
footer { max-width:47rem; margin:0 auto; padding:1.5rem 1.25rem 4rem;
         border-top:1px solid var(--line); color:var(--muted); font-size:.85rem; }

/* Pandoc writes its own syntax colours into a <style> block in the head, and
   they are tuned for a white page: numbers, floats and base-n literals are all
   #0000cf, which on this page's dark background is about 1.4:1 against it —
   `timedelta(seconds=1)` reads as `timedelta(seconds= )`. This stylesheet is
   linked after that block, so redefining the handful of colours that go dark
   is enough; the light palette is left exactly as pandoc chose it. */
@media (prefers-color-scheme: dark) {
  code span.dv, code span.bn, code span.fl { color:#b5cea8; }   /* literals */
  code span.st, code span.ch, code span.vs { color:#a3d18a; }   /* strings */
  code span.co, code span.cn                { color:#9c9c9c; }   /* comments */
  code span.kw, code span.cf                { color:#7fb3ff; }   /* keywords */
  code span.dt, code span.bu                { color:#7fd4c1; }   /* types */
  code span.fu                              { color:#dcb6ff; }   /* functions */
  code span.at, code span.va                { color:#e8e8e8; }
  code span.op, code span.sc                { color:#c9c9c9; }
  code span.er, code span.al                { color:#ff8a5c; }
}
CSS

# A handful of top-level entries with the rest grouped underneath, rather than
# one row of everything. Fourteen in a row was legible at 1600px and wrapped into
# three lines on a laptop, and a navigation nobody can scan is one nobody uses.
#
# Tutorials is the accented one, as it is in Java and .NET: it is the entry
# somebody arriving with no AceMQ at all should land on, and Getting started is
# the same page for somebody who has already decided.
#
# The groups open on hover and on focus, so the keyboard reaches them too, and
# every link is a plain anchor -- the menu needs no JavaScript and still works
# when it is blocked or fails to load.
NAV='<nav class="top">
  <span class="brand"><img src="assets/acemq.png" alt="AceMQ"> for FastAPI</span>
  <a href="index.html">Overview</a>
  <a class="tutorials" href="getting-started.html">Getting started</a>

  <div class="group">
    <button type="button" aria-haspopup="true">Guide</button>
    <div class="menu">
      <a href="lifespan.html">The lifespan</a>
      <a href="consumers.html">Consumers</a>
      <a href="publishing.html">Publishing from a route</a>
      <a href="testing.html">Testing</a>
    </div>
  </div>

  <div class="group">
    <button type="button" aria-haspopup="true">Operations</button>
    <div class="menu">
      <a href="configuration.html">Configuration</a>
      <a href="health.html">Health</a>
      <a href="shutdown.html">Shutdown</a>
      <a href="licence.html">Licence</a>
    </div>
  </div>

  <a class="api" href="apidocs/acemq_fastapi.html">API reference</a>
  <a class="enterprise" href="https://acemq.org/acemq-python-amqp/">Python library</a>
  <a class="enterprise" href="https://acemq.org/">JVM libraries</a>
  <a class="enterprise" href="https://acemq.com">Enterprise support</a>
</nav>
<main>'

FOOT='</main>
<footer>
  <a href="https://github.com/AceMQ-Company/acemq-python-amqp-fastapi">AceMQ for FastAPI</a> &mdash;
  Apache-2.0, and provided without warranty &mdash; see the
  <a href="licence.html">licence</a>.
  <a href="https://acemq.com">Enterprise support</a>.
  The library this wraps is
  <a href="https://acemq.org/acemq-python-amqp/">acemq-amqp</a>, and the JVM
  libraries are at <a href="https://acemq.org/">acemq.org</a>.
  Pre-1.0 and in development.
  FastAPI, Starlette, RabbitMQ and Python are trademarks of their respective
  owners. This project is not affiliated with any of them.
</footer>'

printf '%s' "$NAV" > "$OUT/.nav.html"
printf '%s' "$FOOT" > "$OUT/.foot.html"

render() {
  local source="$1" base="$2" pagetitle="$3"
  pandoc "$source" \
    --from=gfm --to=html5 --standalone \
    --metadata pagetitle="$pagetitle" \
    "${HIGHLIGHT[@]}" \
    --css=style.css \
    --include-before-body="$OUT/.nav.html" \
    --include-after-body="$OUT/.foot.html" \
    --output "$OUT/$base.html"
  # Links between pages are written as .md so they work when the same files are
  # read on GitHub; only the rendered copy is rewritten. The anchor is kept: a
  # link to another page's section is written .md#section and must survive.
  perl -pi -e 's{href="([^":#]*)\.md(#[^"]*)?"}{href="$1.html$2"}g' "$OUT/$base.html"
  # A link to the LICENSE file, which is plain text at the repository root and
  # not a page. On the site it is licence.html.
  perl -pi -e 's{href="LICENSE"}{href="licence.html"}g' "$OUT/$base.html"
  echo "  rendered $base.html"
}

for f in docs/*.md; do
  base="$(basename "${f%.md}")"
  # The first heading is the page title. pagetitle rather than title, because
  # pandoc's template renders a title block from "title" and would print the H1
  # that the markdown already contains.
  title="$(head -n1 "$f" | sed 's/^#\{1,6\} *//')"
  # The overview's own heading is the site's name, and suffixing it produces
  # "AceMQ for FastAPI — AceMQ for FastAPI" in the browser tab.
  if [ "$title" = "AceMQ for FastAPI" ]; then
    pagetitle="$title"
  else
    pagetitle="$title — AceMQ for FastAPI"
  fi

  if [ "$base" = "licence" ]; then
    # The prose about the licence, and then the licence. The text itself is
    # here rather than only in the repository because the site claims to be
    # Apache-2.0 and a claim somebody cannot read is not one they can check.
    { cat "$f"; echo; echo '## The licence itself'; echo; echo '```'; cat LICENSE; echo '```'; } \
      > "$OUT/.licence.md"
    render "$OUT/.licence.md" licence "$pagetitle"
    rm -f "$OUT/.licence.md"
    continue
  fi

  render "$f" "$base" "$pagetitle"
done

rm -f "$OUT/.nav.html" "$OUT/.foot.html"

# The API reference, from the docstrings in src/. Generated from this commit, so
# it cannot describe a version of the library that is not the one beside it.
#
# fastapi and the library have to be importable: pdoc imports what it documents,
# and a module it cannot import becomes a page saying only that.
#
# Every module named rather than the package alone. pdoc respects __all__ when a
# package defines one, and this package's __all__ lists the API's names rather
# than its modules -- so asking for "acemq_fastapi" alone produces a reference
# for whichever modules happen to appear in it and silently omits the rest.
MODULES=$(python3 - <<'MODS'
import pkgutil

import acemq_fastapi

names = ["acemq_fastapi"]
for info in pkgutil.walk_packages(acemq_fastapi.__path__, "acemq_fastapi."):
    names.append(info.name)
print(" ".join(sorted(names)))
MODS
)
echo "  documenting: $MODULES"
# shellcheck disable=SC2086 -- a deliberate word split: one argument per module.
pdoc --output-directory "$OUT/apidocs" \
  --docformat restructuredtext \
  --no-search \
  $MODULES
echo "  rendered apidocs/"

# Jekyll would otherwise skip anything underscore-prefixed.
touch "$OUT/.nojekyll"

echo "Site written to $REPO_ROOT/$OUT/index.html"
